const mongoose = require('mongoose');
const Attendance = require('../models/Attendance');
const { Leave, LeaveBalance } = require('../models/Leave');
const User = require('../models/User');
require('dotenv').config();

const seedAttendanceAndLeave = async () => {
  try {
    // Connect to MongoDB
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/hustle-system', {
      useNewUrlParser: true,
      useUnifiedTopology: true
    });
    console.log('✅ Connected to MongoDB');
    
    console.log('🌱 Starting attendance and leave data seeding...');

    // Get all developers
    const developers = await User.find({ role: 'individual' });
    console.log(`Found ${developers.length} developers`);

    if (developers.length === 0) {
      console.log('No developers found. Please run seedDevelopers.js first.');
      process.exit(1);
    }

    // Clear existing data
    await Attendance.deleteMany({});
    await Leave.deleteMany({});
    await LeaveBalance.deleteMany({});
    console.log('✅ Cleared existing attendance and leave data');

    // Create leave balances for all developers
    for (const dev of developers) {
      await LeaveBalance.create({
        employee: dev._id,
        year: 2025,
        balances: {
          sick: { allocated: 12, used: 0, remaining: 12 },
          casual: { allocated: 12, used: 0, remaining: 12 },
          vacation: { allocated: 21, used: 0, remaining: 21 },
          maternity: { allocated: 180, used: 0, remaining: 180 },
          paternity: { allocated: 15, used: 0, remaining: 15 },
          compensatory: { allocated: 0, used: 0, remaining: 0 }
        }
      });
    }
    console.log('✅ Created leave balances for all developers');

    // Generate attendance for last 30 days
    const today = new Date();
    const startDate = new Date(today);
    startDate.setDate(today.getDate() - 30);

    let totalAttendanceRecords = 0;
    let totalLeaveRecords = 0;

    for (const dev of developers) {
      console.log(`\n📊 Generating data for ${dev.firstName} ${dev.lastName}...`);
      
      const currentDate = new Date(startDate);
      const attendanceRecords = [];
      const leaveRecords = [];

      // Randomly assign 2-3 leave days in the past 30 days
      const leaveDates = [];
      const numLeaveDays = Math.floor(Math.random() * 2) + 2; // 2-3 days
      
      for (let i = 0; i < numLeaveDays; i++) {
        const randomDay = Math.floor(Math.random() * 25) + 1; // Days 1-25
        const leaveDate = new Date(startDate);
        leaveDate.setDate(startDate.getDate() + randomDay);
        
        // Skip weekends
        if (leaveDate.getDay() !== 0 && leaveDate.getDay() !== 6) {
          leaveDates.push(new Date(leaveDate));
        }
      }

      // Create leave applications for leave dates
      for (const leaveDate of leaveDates) {
        const leave = await Leave.create({
          employee: dev._id,
          leaveType: ['sick', 'casual', 'personal'][Math.floor(Math.random() * 3)],
          startDate: leaveDate,
          endDate: leaveDate,
          totalDays: 1,
          reason: 'Personal work',
          status: 'approved',
          managerApproval: {
            status: 'approved',
            approvedAt: new Date(leaveDate.getTime() - 86400000) // 1 day before
          },
          hrApproval: {
            status: 'approved',
            approvedAt: new Date(leaveDate.getTime() - 43200000) // 12 hours before
          },
          attendanceMarked: true,
          appliedDate: new Date(leaveDate.getTime() - 172800000) // 2 days before
        });
        leaveRecords.push(leave);
      }

      // Generate attendance for each day
      while (currentDate <= today) {
        const dayOfWeek = currentDate.getDay();
        
        // Skip weekends (Saturday = 6, Sunday = 0)
        if (dayOfWeek !== 0 && dayOfWeek !== 6) {
          const dateStr = currentDate.toISOString().split('T')[0];
          const isLeaveDay = leaveDates.some(ld => 
            ld.toISOString().split('T')[0] === dateStr
          );

          if (isLeaveDay) {
            // Mark as leave
            const leaveRecord = leaveRecords.find(lr => 
              lr.startDate.toISOString().split('T')[0] === dateStr
            );
            
            const attendance = await Attendance.create({
              employeeId: dev._id,
              employeeCode: dev.email.split('@')[0],
              date: new Date(currentDate),
              status: 'on-leave',
              leaveId: leaveRecord._id,
              isAutoGenerated: true,
              totalWorkingHours: 0
            });
            
            // Update leave record with attendance reference
            leaveRecord.attendanceRecords.push(attendance._id);
            await leaveRecord.save();
            
            attendanceRecords.push(attendance);
          } else {
            // Generate realistic attendance
            const attendanceType = Math.random();
            
            if (attendanceType < 0.85) {
              // 85% present (on time or slightly late)
              // Expected punch in: 11:00 AM, with 70% on time, 30% up to 1 hour late
              const punchInHour = 11 + (Math.random() < 0.7 ? 0 : Math.floor(Math.random() * 2)); // 11 AM or 11-1 PM if late
              const punchInMinute = Math.floor(Math.random() * 60);
              
              // Expected punch out: 7:00 PM, with some variance (6:30 PM - 8:00 PM)
              const punchOutHour = 19 + (Math.random() < 0.5 ? 0 : Math.floor(Math.random() * 2)); // 7-9 PM
              const punchOutMinute = Math.floor(Math.random() * 60);

              const punchInTime = new Date(currentDate);
              punchInTime.setHours(punchInHour, punchInMinute, 0, 0);

              const punchOutTime = new Date(currentDate);
              punchOutTime.setHours(punchOutHour, punchOutMinute, 0, 0);

              const attendance = await Attendance.create({
                employeeId: dev._id,
                employeeCode: dev.email.split('@')[0],
                date: new Date(currentDate),
                punchIn: {
                  time: punchInTime,
                  location: 'Office',
                  ipAddress: '192.168.1.' + Math.floor(Math.random() * 255)
                },
                punchOut: {
                  time: punchOutTime,
                  location: 'Office',
                  ipAddress: '192.168.1.' + Math.floor(Math.random() * 255)
                },
                breaks: [
                  {
                    // Break 1: Lunch at 2:00 PM for 30 minutes
                    breakStart: new Date(new Date(currentDate).setHours(14, 0, 0, 0)),
                    breakEnd: new Date(new Date(currentDate).setHours(14, 30, 0, 0)),
                    breakDuration: 30,
                    breakType: 'lunch'
                  },
                  {
                    // Break 2: Tea at 4:30 PM for 15 minutes
                    breakStart: new Date(new Date(currentDate).setHours(16, 30, 0, 0)),
                    breakEnd: new Date(new Date(currentDate).setHours(16, 45, 0, 0)),
                    breakDuration: 15,
                    breakType: 'tea'
                  }
                ]
              });
              attendanceRecords.push(attendance);
            } else if (attendanceType < 0.95) {
              // 10% partial (only punch in, no punch out)
              const punchInHour = 11 + Math.floor(Math.random() * 2); // 11 AM - 1 PM
              const punchInMinute = Math.floor(Math.random() * 60);

              const punchInTime = new Date(currentDate);
              punchInTime.setHours(punchInHour, punchInMinute, 0, 0);

              const attendance = await Attendance.create({
                employeeId: dev._id,
                employeeCode: dev.email.split('@')[0],
                date: new Date(currentDate),
                punchIn: {
                  time: punchInTime,
                  location: 'Office',
                  ipAddress: '192.168.1.' + Math.floor(Math.random() * 255)
                },
                status: 'partial'
              });
              attendanceRecords.push(attendance);
            } else {
              // 5% absent
              const attendance = await Attendance.create({
                employeeId: dev._id,
                employeeCode: dev.email.split('@')[0],
                date: new Date(currentDate),
                status: 'absent'
              });
              attendanceRecords.push(attendance);
            }
          }
        }

        currentDate.setDate(currentDate.getDate() + 1);
      }

      totalAttendanceRecords += attendanceRecords.length;
      totalLeaveRecords += leaveRecords.length;
      
      console.log(`  ✅ Created ${attendanceRecords.length} attendance records`);
      console.log(`  ✅ Created ${leaveRecords.length} leave records`);
    }

    console.log(`\n🎉 Seeding completed successfully!`);
    console.log(`📊 Total attendance records: ${totalAttendanceRecords}`);
    console.log(`📝 Total leave records: ${totalLeaveRecords}`);
    console.log(`👥 Developers processed: ${developers.length}`);

    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding data:', error);
    process.exit(1);
  }
};

seedAttendanceAndLeave();
