const mongoose = require('mongoose');

const attendanceSchema = new mongoose.Schema({
  employeeId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: [true, 'Employee ID is required']
  },
  employeeCode: {
    type: String,
    required: [true, 'Employee code is required']
  },
  date: {
    type: Date,
    required: [true, 'Date is required'],
    default: () => {
      const today = new Date();
      today.setHours(0, 0, 0, 0);
      return today;
    }
  },
  punchIn: {
    time: {
      type: Date,
      default: null
    },
    location: {
      type: String,
      default: 'Office'
    },
    ipAddress: {
      type: String,
      default: null
    },
    deviceInfo: {
      type: String,
      default: null
    }
  },
  punchOut: {
    time: {
      type: Date,
      default: null
    },
    location: {
      type: String,
      default: 'Office'
    },
    ipAddress: {
      type: String,
      default: null
    },
    deviceInfo: {
      type: String,
      default: null
    }
  },
  totalWorkingHours: {
    type: Number,
    default: 0, // In minutes
    min: [0, 'Working hours cannot be negative']
  },
  status: {
    type: String,
    enum: {
      values: ['present', 'absent', 'partial', 'late', 'early-departure', 'holiday', 'leave', 'on-leave', 'half-leave'],
      message: 'Status must be one of: present, absent, partial, late, early-departure, holiday, leave, on-leave, half-leave'
    },
    default: 'absent'
  },
  breaks: [{
    breakStart: {
      type: Date,
      default: null
    },
    breakEnd: {
      type: Date,
      default: null
    },
    breakDuration: {
      type: Number,
      default: 0 // In minutes
    },
    breakType: {
      type: String,
      enum: ['lunch', 'tea', 'personal', 'meeting', 'other'],
      default: 'lunch'
    }
  }],
  // Leave integration fields
  leaveId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Leave',
    default: null
  },
  isAutoGenerated: {
    type: Boolean,
    default: false
  },
  previousStatus: {
    type: String,
    default: null
  },
  overtime: {
    hours: {
      type: Number,
      default: 0 // In minutes
    },
    approved: {
      type: Boolean,
      default: false
    },
    approvedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null
    }
  },
  notes: {
    type: String,
    maxlength: [500, 'Notes cannot exceed 500 characters'],
    trim: true
  },
  isManualEntry: {
    type: Boolean,
    default: false
  },
  manualEntryBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    default: null
  },
  payrollImpact: {
    deduction: {
      type: Number,
      default: 0
    },
    overtime: {
      type: Number,
      default: 0
    },
    bonus: {
      type: Number,
      default: 0
    }
  },
  isActive: {
    type: Boolean,
    default: true
  },
  // Office timing configuration (for flexible calculations)
  officeTiming: {
    startTime: {
      type: String, // Format: "HH:MM"
      default: '09:30'
    },
    endTime: {
      type: String, // Format: "HH:MM"
      default: '18:00'
    },
    shiftType: {
      type: String,
      enum: ['standard', 'early', 'late', 'flexible', 'custom'],
      default: 'standard'
    }
  }
}, {
  timestamps: true,
  toJSON: { virtuals: true },
  toObject: { virtuals: true }
});

// Virtual for formatted working hours
attendanceSchema.virtual('formattedWorkingHours').get(function() {
  if (this.totalWorkingHours <= 0) return '0h 0m';
  
  const hours = Math.floor(this.totalWorkingHours / 60);
  const minutes = this.totalWorkingHours % 60;
  return `${hours}h ${minutes}m`;
});

// Virtual for employee name
attendanceSchema.virtual('employeeName', {
  ref: 'User',
  localField: 'employeeId',
  foreignField: '_id',
  justOne: true
});

// Index for faster queries
attendanceSchema.index({ employeeId: 1, date: 1 }, { unique: true });
attendanceSchema.index({ date: 1 });
attendanceSchema.index({ status: 1 });
attendanceSchema.index({ employeeCode: 1 });

// Pre-save middleware to calculate working hours and status
attendanceSchema.pre('save', function(next) {
  // Calculate total working hours if punch in and out exist
  if (this.punchIn.time && this.punchOut.time) {
    const workingMinutes = Math.floor((this.punchOut.time - this.punchIn.time) / (1000 * 60));
    
    // Subtract break time
    let totalBreakTime = 0;
    this.breaks.forEach(breakItem => {
      if (breakItem.breakStart && breakItem.breakEnd) {
        const breakMinutes = Math.floor((breakItem.breakEnd - breakItem.breakStart) / (1000 * 60));
        breakItem.breakDuration = breakMinutes;
        totalBreakTime += breakMinutes;
      }
    });
    
    this.totalWorkingHours = Math.max(0, workingMinutes - totalBreakTime);
    
    // Determine status based on working hours
    if (this.totalWorkingHours >= 480) { // 8 hours
      this.status = 'present';
    } else if (this.totalWorkingHours >= 240) { // 4 hours
      this.status = 'partial';
    } else if (this.totalWorkingHours > 0) {
      this.status = 'partial';
    }
    
    // Get office timing (use custom or default)
    const startTime = this.officeTiming?.startTime || '09:30';
    const endTime = this.officeTiming?.endTime || '18:00';
    const shiftType = this.officeTiming?.shiftType || 'standard';
    
    // Check for late arrival (start time + 30 min grace period)
    if (shiftType !== 'flexible') {
      const [startHour, startMin] = startTime.split(':').map(Number);
      const punchInTime = new Date(this.punchIn.time);
      const lateThreshold = new Date(this.date);
      lateThreshold.setHours(startHour, startMin + 30, 0, 0); // Grace period: 30 minutes
      
      if (punchInTime > lateThreshold && this.status === 'present') {
        this.status = 'late';
      }
    }
    
    // Check for early departure (before expected end time)
    if (shiftType !== 'flexible') {
      const [endHour, endMin] = endTime.split(':').map(Number);
      const punchOutTime = new Date(this.punchOut.time);
      const earlyThreshold = new Date(this.date);
      earlyThreshold.setHours(endHour, endMin, 0, 0);
      
      if (punchOutTime < earlyThreshold && this.totalWorkingHours < 480) {
        this.status = 'early-departure';
      }
    }
    
    // Calculate overtime (more than 8 hours)
    if (this.totalWorkingHours > 480) {
      this.overtime.hours = this.totalWorkingHours - 480;
    }
    
  } else if (this.punchIn.time && !this.punchOut.time) {
    // Only punch in, no punch out yet
    this.status = 'partial';
  } else if (!this.punchIn.time && !this.punchOut.time) {
    // No punch in or out
    this.status = 'absent';
  }
  
  next();
});

// Static method to get attendance summary for a date range
attendanceSchema.statics.getAttendanceSummary = async function(employeeId, startDate, endDate) {
  const summary = await this.aggregate([
    {
      $match: {
        employeeId: new mongoose.Types.ObjectId(employeeId),
        date: { $gte: startDate, $lte: endDate },
        isActive: true
      }
    },
    {
      $group: {
        _id: null,
        totalRecords: { $sum: 1 },
        presentDays: { $sum: { $cond: [{ $eq: ['$status', 'present'] }, 1, 0] } },
        absentDays: { $sum: { $cond: [{ $eq: ['$status', 'absent'] }, 1, 0] } },
        partialDays: { $sum: { $cond: [{ $eq: ['$status', 'partial'] }, 1, 0] } },
        lateDays: { $sum: { $cond: [{ $eq: ['$status', 'late'] }, 1, 0] } },
        earlyDepartureDays: { $sum: { $cond: [{ $eq: ['$status', 'early-departure'] }, 1, 0] } },
        leaveDays: { $sum: { $cond: [{ $eq: ['$status', 'leave'] }, 1, 0] } },
        holidayDays: { $sum: { $cond: [{ $eq: ['$status', 'holiday'] }, 1, 0] } },
        totalWorkingMinutes: { $sum: '$totalWorkingHours' },
        totalOvertimeMinutes: { $sum: '$overtime.hours' },
        // Calculate late minutes and early departure minutes would require more complex aggregation
        // For now, we'll handle these in the application layer
        records: {
          $push: {
            date: '$date',
            status: '$status',
            punchIn: '$punchIn.time',
            punchOut: '$punchOut.time',
            totalWorkingHours: '$totalWorkingHours',
            overtime: '$overtime.hours'
          }
        }
      }
    }
  ]);
  
  const result = summary[0] || {
    totalRecords: 0,
    presentDays: 0,
    absentDays: 0,
    partialDays: 0,
    lateDays: 0,
    earlyDepartureDays: 0,
    leaveDays: 0,
    holidayDays: 0,
    totalWorkingMinutes: 0,
    totalOvertimeMinutes: 0,
    records: []
  };

  // Calculate working days in the date range (excluding weekends)
  const calculateWorkingDays = (start, end) => {
    let workingDays = 0;
    const current = new Date(start);
    
    while (current <= end) {
      const dayOfWeek = current.getDay();
      // Exclude Saturdays (6) and Sundays (0)
      if (dayOfWeek !== 0 && dayOfWeek !== 6) {
        workingDays++;
      }
      current.setDate(current.getDate() + 1);
    }
    
    return workingDays;
  };

  const workingDaysInPeriod = calculateWorkingDays(startDate, endDate);
  
  // Calculate additional metrics
  let totalLateMinutes = 0;
  let totalEarlyDepartureMinutes = 0;
  
  if (result.records) {
    result.records.forEach(record => {
      // Calculate late minutes (if punch in is after 9:30 AM)
      if (record.punchIn) {
        const punchInTime = new Date(record.punchIn);
        const expectedTime = new Date(record.date);
        expectedTime.setHours(9, 30, 0, 0);
        
        if (punchInTime > expectedTime) {
          const lateMinutes = Math.floor((punchInTime - expectedTime) / (1000 * 60));
          totalLateMinutes += lateMinutes;
        }
      }

      // Calculate early departure minutes (if punch out is before 5:30 PM)
      if (record.punchOut && record.punchIn) {
        const punchOutTime = new Date(record.punchOut);
        const expectedEndTime = new Date(record.date);
        expectedEndTime.setHours(17, 30, 0, 0);
        
        if (punchOutTime < expectedEndTime) {
          const earlyMinutes = Math.floor((expectedEndTime - punchOutTime) / (1000 * 60));
          totalEarlyDepartureMinutes += earlyMinutes;
        }
      }
    });
  }

  // Enhance the result with calculated metrics
  return {
    ...result,
    workingDaysInPeriod,
    totalLateMinutes,
    totalEarlyDepartureMinutes,
    attendancePercentage: workingDaysInPeriod > 0 ? 
      (((result.presentDays + result.lateDays + result.earlyDepartureDays) / workingDaysInPeriod) * 100).toFixed(1) : 0,
    punctualityPercentage: (result.presentDays + result.lateDays + result.earlyDepartureDays) > 0 ? 
      (((result.presentDays + result.earlyDepartureDays) / (result.presentDays + result.lateDays + result.earlyDepartureDays)) * 100).toFixed(1) : 0
  };
};

// Static method to check if employee already punched in today
attendanceSchema.statics.getTodayAttendance = async function(employeeId) {
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  
  const tomorrow = new Date(today);
  tomorrow.setDate(tomorrow.getDate() + 1);
  
  return await this.findOne({
    employeeId,
    date: { $gte: today, $lt: tomorrow },
    isActive: true
  });
};

module.exports = mongoose.model('Attendance', attendanceSchema);